site_name: "Réponse à l'Appel d'Offre Audit CISAC"

nav:
  - Home: index.md
  - Proposition:
      - proposal/index.md
      - Contexte: proposal/context-introduction.md
      - Gouvernance: proposal/governance.md
      - Facteurs clés: proposal/key-success-factors.md
      - Planification: proposal/planning.md
      - À propos CISAC: proposal/what-is-cisac.md
      - Document complet: proposal/md/CISAC Audit/CISAC Audit.md
  - Docs de Travail:
      - docs_de_travail/index.md
      - Synchro PALO: 2025-07-11-CISAC-Synchro-avec-PALO.md
  - Resources:
      - resources/index.md
      - Standard ISO15707: resources/ISO15707.md
      - Vue d'ensemble CISAC: resources/[ChatGPT]CISAC-and-ISWC-administration-governance-overview.md
      - RFP Original: resources/md/RFP_ISWC_Audit-v1.1/RFP_ISWC_Audit-v1.1.md

docs_dir: docs

# Theme configuration using material
theme:
  name: material
  favicon: img/favicon.ico
  palette:
    primary: custom
    accent: custom
  font:
    text: Montserrat
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

# Custom CSS with TERAGONE FACTORY branding
extra_css:
  - css/palo-it-mkdocs-theme.css

# Extra settings
extra:
  generator: false

# Footer customization
copyright: Copyright &copy; 2025 TERAGONE FACTORY. All rights reserved.

# Plugins
plugins:
  - search
  - mermaid2

# Mermaid configuration
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - tables
  - footnotes
