[project]
name = "CISAC_Audit_Response"
version = "0.1.0"
description = "Réponse à l'appel d'offre d'audit CISAC"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.12",
    "mkdocs-mermaid2-plugin>=1.2.1",
]
