ALTER TABLE [ISWC].[Creator] DROP CONSTRAINT [FK_Creator_ISWC_IswcID]
GO

ALTER TABLE [ISWC].[ISWCLinkedTo] DROP CONSTRAINT [FK_ISWCLinkedTo_ISWC_IswcID]
GO

ALTER TABLE [ISWC].[Publisher] DROP CONSTRAINT [FK_Publisher_ISWC_IswcID]
GO

ALTER TABLE [ISWC].[Title] DROP CONSTRAINT [FK_Title_ISWC_IswcID]
GO

ALTER TABLE [ISWC].[WorkInfo] DROP CONSTRAINT [FK_WorkInfo_ISWC_IswcID]
GO


-- Create the ISWC table partition Primary Clustered Key
ALTER TABLE [ISWC].[ISWC]  WITH NOCHECK ADD  
CONSTRAINT [PK_ISWC] PRIMARY KEY CLUSTERED
(
	[IswcID] ASC
)WITH (PAD_INDEX=OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON) on [part_scheme_PartitionByISWCID] ([IswcID])
GO


ALTER TABLE [ISWC].[Creator]  WITH CHECK ADD  CONSTRAINT [FK_Creator_ISWC_IswcID] FOREIGN KEY([IswcID])
REFERENCES [ISWC].[ISWC] ([IswcID])
GO
ALTER TABLE [ISWC].[Creator] CHECK CONSTRAINT [FK_Creator_ISWC_IswcID]
GO
ALTER TABLE [ISWC].[ISWCLinkedTo]  WITH CHECK ADD  CONSTRAINT [FK_ISWCLinkedTo_ISWC_IswcID] FOREIGN KEY([IswcID])
REFERENCES [ISWC].[ISWC] ([IswcID])
GO
ALTER TABLE [ISWC].[ISWCLinkedTo] CHECK CONSTRAINT [FK_ISWCLinkedTo_ISWC_IswcID]
GO
ALTER TABLE [ISWC].[Publisher]  WITH NOCHECK ADD  CONSTRAINT [FK_Publisher_ISWC_IswcID] FOREIGN KEY([IswcID])
REFERENCES [ISWC].[ISWC] ([IswcID])
GO
ALTER TABLE [ISWC].[Publisher] CHECK CONSTRAINT [FK_Publisher_ISWC_IswcID]
GO
ALTER TABLE [ISWC].[Title]  WITH NOCHECK ADD  CONSTRAINT [FK_Title_ISWC_IswcID] FOREIGN KEY([IswcID])
REFERENCES [ISWC].[ISWC] ([IswcID])
GO
ALTER TABLE [ISWC].[Title] CHECK CONSTRAINT [FK_Title_ISWC_IswcID]
GO
ALTER TABLE [ISWC].[WorkInfo]  WITH NOCHECK ADD  CONSTRAINT [FK_WorkInfo_ISWC_IswcID] FOREIGN KEY([IswcID])
REFERENCES [ISWC].[ISWC] ([IswcID])
GO
ALTER TABLE [ISWC].[WorkInfo] CHECK CONSTRAINT [FK_WorkInfo_ISWC_IswcID]
GO