CREATE TABLE [ISWC].[MergeRequest] (
    [MergeRequestID]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [AgencyID]           CHAR (3)      NOT NULL,
    [MergeStatus]        INT           NOT NULL,
    [Status]             BIT           NOT NULL,
    [Concurrency]        ROWVERSION    NOT NULL,
    [CreatedDate]        DATETIME2 (0) NOT NULL,
    [LastModifiedDate]   DATETIME2 (0) NOT NULL,
    [LastModifiedUserID] INT           NOT NULL,
    [MergeType]          INT           NULL,
    CONSTRAINT [PK_MergeRequest] PRIMARY KEY CLUSTERED ([MergeRequestID] ASC),
    CONSTRAINT [FK_MergeRequest_Agency_AgencyID] FOREIGN KEY ([AgencyID]) REFERENCES [Lookup].[Agency] ([AgencyID]),
    CONSTRAINT [FK_MergeRequest_MergeStatus_MergeStatusID] FOREIGN KEY ([MergeStatus]) REFERENCES [Lookup].[MergeStatus] ([MergeStatusID]),
    CONSTRAINT [FK_MergeRequest_User_LastModifiedUserID] FOREIGN KEY ([LastModifiedUserID]) REFERENCES [Lookup].[User] ([UserID])
);




GO
CREATE NONCLUSTERED INDEX [IX_MergeRequest_AgencyID]
    ON [ISWC].[MergeRequest]([AgencyID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_MergeRequest_LastModifiedUserID]
    ON [ISWC].[MergeRequest]([LastModifiedUserID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Unique autogenerated ID for the merge request', @level0type = N'SCHEMA', @level0name = N'ISWC', @level1type = N'TABLE', @level1name = N'MergeRequest', @level2type = N'COLUMN', @level2name = N'MergeRequestID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'CISAC agency code reference of the agency who made the request', @level0type = N'SCHEMA', @level0name = N'ISWC', @level1type = N'TABLE', @level1name = N'MergeRequest', @level2type = N'COLUMN', @level2name = N'AgencyID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = '0 (Pending), 1 (Complete)', @level0type = N'SCHEMA', @level0name = N'ISWC', @level1type = N'TABLE', @level1name = N'MergeRequest', @level2type = N'COLUMN', @level2name = N'MergeStatus';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Logically deleted status', @level0type = N'SCHEMA', @level0name = N'ISWC', @level1type = N'TABLE', @level1name = N'MergeRequest', @level2type = N'COLUMN', @level2name = N'Status';

GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Row version field', @level0type = N'SCHEMA', @level0name = N'ISWC', @level1type = N'TABLE', @level1name = N'MergeRequest', @level2type = N'COLUMN', @level2name = N'Concurrency';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Date that the entity instance was created', @level0type = N'SCHEMA', @level0name = N'ISWC', @level1type = N'TABLE', @level1name = N'MergeRequest', @level2type = N'COLUMN', @level2name = N'CreatedDate';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Date of last modification', @level0type = N'SCHEMA', @level0name = N'ISWC', @level1type = N'TABLE', @level1name = N'MergeRequest', @level2type = N'COLUMN', @level2name = N'LastModifiedDate';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'The last modifying user ', @level0type = N'SCHEMA', @level0name = N'ISWC', @level1type = N'TABLE', @level1name = N'MergeRequest', @level2type = N'COLUMN', @level2name = N'LastModifiedUserID';
